### ISSUE TITLE
イメージサイズ削減大作戦

### ISSUE THREAD

**Issue by sksat** [WORD-COINS/latex-build#13]
@puripuri2100 曰く，「latexのパッケージは異常にPDFになったドキュメントが入ってるせいでサイズがデカくなっているのでそいつらを一掃するとかなり小さくなる」とのこと

**Comment by sksat** [comment]
PDF，いるにはいるけど別にそんなにいないな

**Comment by rizaudo** [comment]
いやそんな物大体対策してるイメージだよ。入ってncduかけてみるとわかるけど、今のイメージで一番デカイのはフォントだね。

**Comment by sksat** [comment]
そうぽい(中身見てました)

**Comment by sksat** [comment]
無理じゃね？

**Comment by puripuri2100** [comment]
えっ（知らなかった）

**Comment by rizaudo** [comment]
自分含め歴代TeXヒューマンが頑張った結果なので、フォント削減案とか案が出てきた時には頑張ってみて欲しい。

現状では細い回線持ち向けとか考えたとしても多分これが一番コストパフォーマンスに優れた作りだと思う。

**Comment by sksat** [comment]
self-hosted runnerにして別でフォント持っておいて差し込むとかは可能ではあるけど全然うまみないのでこれでよさそう

**Comment by rizaudo** [comment]
結局フォント差し込むなら`fc-cache`という遅い物を一々叩き直す必要が増えて、フォント後刺しやめといた方が良いかなーという印象ね。
